### PR TITLE
CRAN release 1.2.0

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by msevestre** [comment]
some merge issue going on here

**Comment by IndrajeetPatil** [comment]
But how can there be merge issues if I am trying to update `main` branch with newer commits in `develop`?

**Comment by msevestre** [comment]
Did you push directly to main?

**Comment by IndrajeetPatil** [comment]
Nope. The last commit in `main` is the squash and merge I did for `1.1.0` release. Can that be the issue?

**Comment by msevestre** [comment]
Yes it can be the issue. But you should not have merge conflicts. If you look at the actual conflicts, what branch is valid? Develop or main?

**Comment by IndrajeetPatil** [comment]
> what branch is valid?

What do you mean by _valid_ here?

**Comment by msevestre** [comment]
Are you going to fix the merge conflicts? @IndrajeetPatil

**Comment by IndrajeetPatil** [comment]
I can, but does this mean every time we have a new release, I need to manually change every single file that was changed?!

**Comment by msevestre** [comment]
No I never had this issue before. So this has do to with the way the merge was done or the branch created etc..

LEt's NOT SQUASH AND MERGE on master. I am happy to create the next release so that it is as it should and we should check if we have more discrepancies

**Comment by IndrajeetPatil** [comment]
Sounds good. 

I will let you merge this one in the main.

**Comment by IndrajeetPatil** [comment]
Btw, in case you didn't know, CRAN also has a mirror on GitHub that also acts like a _main_ branch for this package:

https://github.com/cran/ospsuite.utils

**Pull request merged**
