### PR TITLE
Adds `objectCount()` function

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
Currently, used only in `DataCombined`, but it is useful across all plotting functions to make sure that only a single class instance has been entered.

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Ideally to be merged after #87 has been merged.

**Comment by PavelBal** [comment]
There are already functions `isSameLength` and `isOfLength`. Could you explain the differences between them and the new function? I wouldn't know when to use which function.

**Comment by IndrajeetPatil** [comment]
- `isSameLength()`: **Checks** if a collection of objects have same **length**.
- `isOfLength`: **Checks** if object(s) have the expected **length**.

- `objCount`: **Computes** the **count** (and not length) of objects. It doesn't check for anything.

`objCount()` can be combined with validation functions. 

For example,

```r
# make sure that only a single class instance has been entered
isOfLength(objCount(dataCombined), 1L) # TRUE
isOfLength(objCount(list(dataCombined1, dataCombined2)), 1L) # FALSE
```

**Comment by PavelBal** [comment]
This does not work:

```
> ds <- DataSet$new("ds1")
> objectCount(ds)
[1] 21
```

**Comment by IndrajeetPatil** [comment]
Good catch!

I was testing with `Printable`, which turned out to be a bad example.

``` r
library(ospsuite)
#> Loading required package: rClr
#> Loading the dynamic library for Microsoft .NET runtime...
#> Loaded Common Language Runtime version 4.0.30319.42000
library(ospsuite.utils)

x <- DataCombined$new()
y <- DataSet$new(name = "x")

objectCount(x)
#> [1] 1
objectCount(y)
#> [1] 1
objectCount(list(x, y))
#> [1] 2
```

<sup>Created on 2022-03-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Review by PavelBal — APPROVED** [review]

**Pull request merged**
